schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "i-know-flowchart"
owner:
  username: "s246568"
  id: 253249487
  accepted_at: "2026-09-01T10:53:28Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
